version: '3.1'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    container_name: mysqldb-container
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    volumes:
      - mydb:/var/lib/mysql
    networks:
      - database_net

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - cache_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-webapp
    container_name: webapp-container
    depends_on:
      - mysqldb
    restart: on-failure
    env_file: ./.env
    ports:
      - "8095:8080"
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_HOST: mysqldb
      MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      JPA_HIBERNATE_DDL: $JPA_HIBERNATE_DDL
      MYSQL_PORT: $MYSQLDB_DOCKER_PORT
      REDIS_HOST: cache
    networks:
      - database_net
      - cache_net




volumes:
  mydb:

networks:
  database_net:
  cache_net:
