version: '3.1'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    container_name: mysqldb-container
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    volumes:
      - my-db:/var/lib/mysql


  app:
    build: .
    image: srping-webapp
    container_name: webapp-container
    depends_on:
      - mysqldb
    restart: on-failure
    env_file: ./.env
    ports:
      - "8095:8080"
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_HOST: mysqldb
      MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      JPA_HIBERNATE_DDL: $JPA_HIBERNATE_DDL
      MYSQL_PORT: 3306



volumes:
  my-db: