spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DATABASE:testdb}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:springboot}
    password: ${MYSQL_PASSWORD:springbootdata}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL:create}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

logging:
  level:
    root: warn